services:
  supabase:
    image: supabase/postgres:15.1.0.147
    ports:
      - '54322:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle
    volumes:
      - ./data/tigerbeetle:/data
    ports:
      - '3000:3000'
    command: ['start', '--addresses=0.0.0.0:3000', '/data/0_0.tigerbeetle']
